<?php

namespace Lumen\AppBundle\Repository;

/**
 * AsistentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistentesRepository extends \Doctrine\ORM\EntityRepository
{
}
