<?php

namespace Lumen\AppBundle\Repository;

/**
 * CategoriaAnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaAnalisisRepository extends \Doctrine\ORM\EntityRepository
{
}
