<?php

namespace Lumen\AppBundle\Repository;

/**
 * CategoriaServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaServiciosRepository extends \Doctrine\ORM\EntityRepository
{
}
