<?php

namespace Lumen\AppBundle\Repository;

/**
 * CodigoMuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoMuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
