<?php

namespace Lumen\AppBundle\Repository;

/**
 * DetalleMuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleMuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
