<?php

namespace Lumen\AppBundle\Repository;

/**
 * MesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesRepository extends \Doctrine\ORM\EntityRepository
{
}
