<?php

namespace Lumen\AppBundle\Repository;

/**
 * MuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
