<?php

namespace Lumen\AppBundle\Repository;

/**
 * SolicitudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudesRepository extends \Doctrine\ORM\EntityRepository
{
}
