<?php

namespace Lumen\AppBundle\Repository;

/**
 * SolicitudDeServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudDeServiciosRepository extends \Doctrine\ORM\EntityRepository
{
}
