<?php

namespace Lumen\AppBundle\Repository;

/**
 * TipoAsistentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAsistentesRepository extends \Doctrine\ORM\EntityRepository
{
}
