<?php

namespace Lumen\AppBundle\Repository;

/**
 * TipoMuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
