<?php

namespace Lumen\AppBundle\Repository;

/**
 * TipoAnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAnalisisRepository extends \Doctrine\ORM\EntityRepository
{
}
