Cliente:
    type: entity
    table: Cliente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        empresa:
            type: integer
            nullable: false
            options:
                unsigned: false
        clave:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
