lumen_app:
    resource: "@LumenAppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    defaults:
        _locale: es
    requirements:
        _locale: en|es

cliente_app:
    resource: "@LumenAppBundle/Controller/ClienteController.php"
    type:     annotation
    prefix:   /cliente
    defaults:
        _locale: es
    requirements:
         _locale: en|es
admin_app:
    resource: "@LumenAppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    defaults:
        _locale: es
    requirements:
         _locale: en|es


#rest:
#  type: rest
#  prefix: /rest
#  resource: "Lumen\AppBundle\Controller\RestV1Controller"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile


#elfinder:
#     resource: "@FMElfinderBundle/Resources/config/routing.yml"

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#comur_image:
#    resource: "@ComurImageBundle/Resources/config/routing.yml"
#    prefix:   /

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

lumen_app_bundle_index:
    path:      /index
    defaults:  { _controller: LumenAppBundle:Default:index }

lumen_app_bundle_login:
    path:      /cliente/loginInicio
    defaults:  { _controller: LumenAppBundle:Cliente:loginc }

lumen_app_bundle_logout:
    path:      /cliente/logout
    defaults:  { _controller: LumenAppBundle:Cliente:logout }

lumen_app_bundle_registro:
    path:      /cliente/registroInicio
    defaults:  { _controller: LumenAppBundle:Cliente:registro }

lumen_app_bundle_indexClient:
    path:      /cliente/index
    defaults:  { _controller: LumenAppBundle:Cliente:indexclient }

lumen_app_bundle_indexAdmin:
    path:      /admin/index
    defaults:  { _controller: LumenAppBundle:Admin:indexAdmin }

