# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    lumen.twig.load_javascrip:
        class: Lumen\ImportsBundle\Twig\Extension\LoadJavascriptExtension
        arguments:    [@session]
        tags :
            - { name: twig.extension }
    lumen.twig.user_avatar:
        class: Application\Sonata\UserBundle\Twig\Extension\UserAvatarExtension
        arguments:    [@security.context, @twig]
        tags :
            - { name: twig.extension }
    lumen_auth_success_handler:
        class: Application\Sonata\UserBundle\Services\LoginSuccessHandler
        arguments: [@security.context, @router]
        tags:
            - { name: monolog.logger, channel: security }
    lumen_appbundle.field_image_custom:
        class: Lumen\AppBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: image_custom }
