sonata_admin:
    title:      'Beaker'
    title_logo: /img/logotype/logo.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::layout.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            User:
                label: Users
                items:
                    - sonata.user.admin.user
                    #- sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN]

            Administrativo:
                label: Administrativo
                items:
                     - lumen_app.admin.cliente
                     - lumen_app.admin.categoria_analisis
                     - lumen_app.admin.analisis
                     - lumen_app.admin.muestra
                     - lumen_app.admin.detalle_muestra
                    #- sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN]
            Asistentes:
                 label: Asistentes
                 items:
                      - lumen_app.admin.tipo_asistentes
                      - lumen_app.admin.asistentes
                      -

                 roles: [ROLE_SUPER_ADMIN]







