sonata_admin:
    title:      'Beaker'
    title_logo: /img/logotype/logo.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::layout.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            User:
                label: Users
                items:
                    - sonata.user.admin.user
                    #- sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN]

            Administrativo:
                label: Administrativo
                items:
                    - lumen_app.admin.categoria_servicios
                    - lumen_app.admin.servicios
                    - lumen_app.admin.muestra
                    - lumen_app.admin.solicitudes
                    - lumen_app.admin.tipo_muestra
                    - lumen_app.admin.cliente
                    - lumen_app.admin.empresa
                    #- sonata.user.admin.group
                roles: [ROLE_SUPER_ADMIN]






