<?php

namespace Application\Sonata\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Application\Sonata\UserBundle\Controller\UserAdminController();
        return $instance;
    }
}
