<?php

namespace Comur\ImageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UploadController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Comur\ImageBundle\Controller\UploadController();
        return $instance;
    }
}
