<?php

namespace Lumen\SonataExtendsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CustomAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Lumen\SonataExtendsBundle\Controller\CustomAdminController();
        return $instance;
    }
}
