services:
    Beaker.sontaextends.extendsblock:
        id: Beaker.sontaextends.extendsblock
        class: Beaker\SonataExtendsBundle\Block\ExtendsBlockService
        arguments:
            - @service_container
            - Beaker.sontaextends.extendsblock
            - @templating
        tags:
            - { name: sonata.block }
            
    sonata.admin.Beaker.extends.base:
        class: Beaker\SonataExtendsBundle\Admin\FakeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "BeakerExtendsBaseAdmin", label: "BeakerExtendsBaseAdmin" }
        arguments:
            - ~
            - Beaker\SonataExtendsBundle\Entity\FakeEntity
            - ~
        calls:
            - [ setTranslationDomain, [BeakerSonataExtendsBundle]]
            
